<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::pluck('id', 'slug')->toArray();

        $products = [
            // CƠM GÀ (rice)
            [
                'category_id' => $categories['rice'] ?? 1,
                'name' => 'Cơm Gà Sốt Cay',
                'slug' => 'com-ga-sot-cay',
                'description' => 'Đùi gà chiên giòn rụm phủ đẫm sốt cay ngọt Hàn Quốc, ăn kèm cơm dẻo và dưa chua.',
                'price' => 49000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=700&q=80',
                'tag' => 'BEST SELLER',
                'rating' => 4.9,
                'review_count' => 384,
                'subtag' => '🍚 Cơm dẻo + Gà sốt cay',
                'default_sauce' => 'Sốt Cay Hàn',
                'is_hot' => true,
                'is_available' => true,
                'order' => 1,
            ],
            [
                'category_id' => $categories['rice'] ?? 1,
                'name' => 'Cơm Gà Sốt Mật Ong',
                'slug' => 'com-ga-sot-mat-ong',
                'description' => 'Gà giòn óng ả phủ sốt mật ong hoa rừng ngọt dịu, ăn cùng cơm nóng và dưa góp thanh mát.',
                'price' => 49000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 4.8,
                'review_count' => 256,
                'subtag' => '🍯 Cơm nóng + Gà sốt mật ong',
                'default_sauce' => 'Sốt Mật Ong',
                'is_hot' => true,
                'is_available' => true,
                'order' => 2,
            ],
            [
                'category_id' => $categories['rice'] ?? 1,
                'name' => 'Cơm Gà Bơ Tỏi',
                'slug' => 'com-ga-bo-toi',
                'description' => 'Gà vàng ươm tẩm sốt bơ tỏi thơm nức, rắc tỏi phi giòn tan, vị béo ngậy cuốn hút khó cưỡng.',
                'price' => 49000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=700&q=80',
                'tag' => 'MỚI',
                'rating' => 4.9,
                'review_count' => 198,
                'subtag' => '🧄 Gà tỏi thơm giòn đậm đà',
                'default_sauce' => 'Sốt Bơ Tỏi',
                'is_hot' => true,
                'is_available' => true,
                'order' => 3,
            ],
            [
                'category_id' => $categories['rice'] ?? 1,
                'name' => 'Cơm Gà Sốt Chua Ngọt',
                'slug' => 'com-ga-sot-chua-ngot',
                'description' => 'Gà giòn tan quyện sốt chua ngọt bắt vị, thanh mát giải ngấy cho bữa trưa đầy năng lượng.',
                'price' => 49000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 4.7,
                'review_count' => 142,
                'subtag' => '🥭 Cơm dẻo + Sốt chua ngọt',
                'default_sauce' => 'Sốt Chua Ngọt',
                'is_hot' => false,
                'is_available' => true,
                'order' => 4,
            ],

            // GÀ SỐT (chicken)
            [
                'category_id' => $categories['chicken'] ?? 2,
                'name' => 'Gà Sốt Cay (Phần Lớn)',
                'slug' => 'ga-sot-cay-phan-lon',
                'description' => 'Gà không xương giòn rụm đẫm sốt cay đỏ óng ả, rắc mè rang thơm bùi chuẩn vị Hàn Quốc.',
                'price' => 45000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 4.9,
                'review_count' => 310,
                'subtag' => '🍗 6-8 miếng gà phủ sốt',
                'default_sauce' => 'Sốt Cay Hàn',
                'is_hot' => true,
                'is_available' => true,
                'order' => 5,
            ],
            [
                'category_id' => $categories['chicken'] ?? 2,
                'name' => 'Gà Sốt Mật Ong (Phần Lớn)',
                'slug' => 'ga-sot-mat-ong-phan-lon',
                'description' => 'Phần gà chiên giòn tẩm sốt mật ong thơm phức, lớp da bóng bẩy cuốn hút mọi lứa tuổi.',
                'price' => 45000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1527477321055-43615862e771?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 4.8,
                'review_count' => 215,
                'subtag' => '🍗 Gà giòn sốt mật ong',
                'default_sauce' => 'Sốt Mật Ong',
                'is_hot' => false,
                'is_available' => true,
                'order' => 6,
            ],
            [
                'category_id' => $categories['chicken'] ?? 2,
                'name' => 'Gà Sốt Bơ Tỏi (Phần Lớn)',
                'slug' => 'ga-sot-bo-toi-phan-lon',
                'description' => 'Gà giòn thơm nức mùi bơ tỏi phi, béo bùi ngập tràn từng miếng cắn.',
                'price' => 45000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 4.8,
                'review_count' => 188,
                'subtag' => '🧄 Gà bơ tỏi thơm lừng',
                'default_sauce' => 'Sốt Bơ Tỏi',
                'is_hot' => false,
                'is_available' => true,
                'order' => 7,
            ],

            // ĂN KÈM (side)
            [
                'category_id' => $categories['side'] ?? 4,
                'name' => 'Khoai Tây Chiên Giòn',
                'slug' => 'khoai-tay-chien-gion',
                'description' => 'Khoai tây cắt thanh chiên vàng giòn rụm, lắc muối tiêu thơm ngon.',
                'price' => 20000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 4.7,
                'review_count' => 175,
                'subtag' => '🍟 Khoai tây chiên',
                'default_sauce' => null,
                'is_hot' => false,
                'is_available' => true,
                'order' => 8,
            ],
            [
                'category_id' => $categories['side'] ?? 4,
                'name' => 'Trứng Ốp La Lòng Đào',
                'slug' => 'trung-op-la-long-dao',
                'description' => 'Trứng gà tươi ốp la lòng đào béo ngậy, chảy tràn trên cơm nóng hấp dẫn.',
                'price' => 10000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 4.9,
                'review_count' => 290,
                'subtag' => '🍳 Topping cơm gà',
                'default_sauce' => null,
                'is_hot' => false,
                'is_available' => true,
                'order' => 9,
            ],

            // ĐỒ UỐNG (drink)
            [
                'category_id' => $categories['drink'] ?? 5,
                'name' => 'Coca Cola (Lon 320ml)',
                'slug' => 'coca-cola-lon-320ml',
                'description' => 'Coca Cola mát lạnh đã khát, uống kèm gà chiên giòn chuẩn vị.',
                'price' => 12000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 5.0,
                'review_count' => 420,
                'subtag' => '🥤 Nước ngọt có gas',
                'default_sauce' => null,
                'is_hot' => false,
                'is_available' => true,
                'order' => 10,
            ],
            [
                'category_id' => $categories['drink'] ?? 5,
                'name' => 'Pepsi (Lon 320ml)',
                'slug' => 'pepsi-lon-320ml',
                'description' => 'Pepsi ướp lạnh sảng khoái, giải ngấy tức thì sau từng miếng gà.',
                'price' => 12000,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=700&q=80',
                'tag' => null,
                'rating' => 5.0,
                'review_count' => 310,
                'subtag' => '🥤 Nước ngọt ướp lạnh',
                'default_sauce' => null,
                'is_hot' => false,
                'is_available' => true,
                'order' => 11,
            ],

            // COMBO (combo)
            [
                'category_id' => $categories['combo'] ?? 3,
                'name' => 'COMBO SOLO',
                'slug' => 'combo-solo',
                'description' => '1 Cơm gà sốt tuỳ chọn + 1 Nước ngọt có gas.',
                'price' => 69000,
                'original_price' => 64000,
                'image' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80',
                'tag' => 'TIẾT KIỆM',
                'rating' => 4.9,
                'review_count' => 150,
                'subtag' => 'Dành cho 1 người',
                'default_sauce' => 'Sốt Cay Hàn',
                'is_hot' => false,
                'is_available' => true,
                'order' => 12,
            ],
            [
                'category_id' => $categories['combo'] ?? 3,
                'name' => 'COMBO DUO',
                'slug' => 'combo-duo',
                'description' => '2 Cơm gà sốt tuỳ chọn + 2 Nước ngọt + 1 Khoai tây lắc.',
                'price' => 99000,
                'original_price' => 149000,
                'image' => 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=700&q=80',
                'tag' => 'BÁN CHẠY NHẤT',
                'rating' => 5.0,
                'review_count' => 280,
                'subtag' => 'Ăn no gà — 2 người',
                'default_sauce' => 'Sốt Cay Hàn',
                'is_hot' => false,
                'is_available' => true,
                'order' => 13,
            ],
            [
                'category_id' => $categories['combo'] ?? 3,
                'name' => 'COMBO FULL',
                'slug' => 'combo-full',
                'description' => '1 Mẹt gà sốt 8 miếng + 1 Gà popcorn + 1 Khoai chiên + 3 Nước ngọt.',
                'price' => 149000,
                'original_price' => 262000,
                'image' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=700&q=80',
                'tag' => 'TIẾT KIỆM',
                'rating' => 4.9,
                'review_count' => 190,
                'subtag' => 'Party ngập tràn — 3-4 người',
                'default_sauce' => 'Sốt Cay Hàn',
                'is_hot' => false,
                'is_available' => true,
                'order' => 14,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
